alias ls='ls --color=auto'
alias la='ls -lA --color=auto'
alias ll='ls -l --color=auto'
alias lh='ls -lh --color=auto'
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ping='ping -c 4'
alias lping='/usr/bin/ping'
alias pacman='pacman --color=auto'
alias sudo='sudo '
