export XDG_DESKTOP_DIR="${HOME}/desktop"
export XDG_DOCUMENTS_DIR="${HOME}/docs"
export XDG_DOWNLOAD_DIR="${HOME}/downloads"
export XDG_MUSIC_DIR="${HOME}/music"
export XDG_PICTURES_DIR="${HOME}/pics"
export XDG_VIDEOS_DIR="${HOME}/videos"
export XDG_TEMPLATES_DIR="${HOME}/templates"
